/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegotesting;

/**
 *
 * @author JAMES
 */
public class PrimeraEtapa extends javax.swing.JFrame {

    /**
     * Creates new form PrimeraEtapa
     */
    public PrimeraEtapa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ducha = new javax.swing.JButton();
        Mochila = new javax.swing.JButton();
        CorrerClases = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ducha.setText("Tomar ducha");
        Ducha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuchaActionPerformed(evt);
            }
        });

        Mochila.setText("Alistar la mochila");
        Mochila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MochilaActionPerformed(evt);
            }
        });

        CorrerClases.setText("Agarrar todo e ir corriendo a clases");
        CorrerClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrerClasesActionPerformed(evt);
            }
        });

        jLabel1.setText("Buenas días, ¡apurate tienes que ir a la escuela!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Ducha)
                        .addGap(18, 18, 18)
                        .addComponent(Mochila)
                        .addGap(18, 18, 18)
                        .addComponent(CorrerClases))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ducha)
                    .addComponent(Mochila)
                    .addComponent(CorrerClases))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DuchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuchaActionPerformed
        Ducha frame = new Ducha();
            frame.setVisible(true);
            dispose();
    }//GEN-LAST:event_DuchaActionPerformed

    private void MochilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MochilaActionPerformed
        Mochila frame = new Mochila();
            frame.setVisible(true);
            dispose();
    }//GEN-LAST:event_MochilaActionPerformed

    private void CorrerClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrerClasesActionPerformed
        CorrerClase frame = new CorrerClase();
            frame.setVisible(true);
            dispose();
    }//GEN-LAST:event_CorrerClasesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeraEtapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeraEtapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeraEtapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeraEtapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeraEtapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CorrerClases;
    private javax.swing.JButton Ducha;
    private javax.swing.JButton Mochila;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
